### ISSUE TITLE
Please use own Staticman instance

### ISSUE THREAD

**Issue by VincentTam** [Alamantus/robbie.antenesse.net#46]
Hi, this is the owner of @<span>staticmanlab</span>, the former Staticman bot account that you've invited.

I'm writing to you as I've decided to stop the service last weekend because of Staticman's maintainer's recommendations in https://github.com/eduardoboucas/staticman/issues/317#issuecomment-565250060 to move away from the public instance.

As a result, I've posted https://github.com/daattali/beautiful-jekyll/pull/775, whose description contains an illustrated guide for setting up a self-hosted Staticman instance.

**Comment by Alamantus** [comment]
Thanks for letting me know! I've disabled comments, and I'll remove staticmanlab from the repo.
